include:
  - utils.compose.yml
  - authentik.compose.yml

services:
  sftpgo:
    image: drakkan/sftpgo
    volumes:
      - ./sftpgo/banner.txt:/etc/sftpgo/banner.txt:ro
      - ./sftpgo/env.d/:/etc/sftpgo/env.d/:ro
      - ./tls/wildcard.crt:/etc/ssl/certs/wildcard.crt:ro
    environment:
      SSL_CERT_FILE: /etc/ssl/certs/wildcard.crt

      SFTPGO_CONFIG_DIR: /etc/sftpgo
